### ISSUE TITLE
Updating the default_renderer (djot parsing)

### ISSUE THREAD

**Issue by tomouellette** [lustre-labs/ssg#20]
Hi! I've found lustre/lustre_ssg to be pretty useful for writing a static site generator for some simple code documentation I'm making. I've been using the `default_renderer` on `.djot` files but it seems to miss a lot of the common syntax in `djot` (e.g. lists, classes, math, etc). Is there plans on improving the renderer or, alternatively, would upgrading from `jot v0.4.0` to `jot v0.5.0` improve things? Thanks.

**Comment by hayleigh-dot-dev** [comment]
Looks like jot 0.5.0 added inline code. Unfortunately I don't maintain jot and it's the only package around that provides an AST that we can turn into Lustre elements.

I'd welcome more development on that package but I already work on enough as it is ^.^ If a more-featured markdown or djot parser comes around that emits AST rather than HTML strings I'd happily switch to it but so far this is the best we have :c 

---

I've published 0.7.0 that updates jot to 0.5.0, best I can do on my end!
